import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { createClient } from "next-sanity";
import { Navigation } from "../components/Global/Navigation";
import Script from "next/script";
import { HomeBanner } from "../components/HomeComponents/HomeBanner";
import { HomeCategory } from "../components/HomeComponents/HomeCategory";
import { ProductContainer } from "../components/HomeComponents/ProductContainer";
import { useState } from "react";
import modalPic from "../public/images/newsletter.png";
import jewellery1 from "../public/images/products/jewellery-1.jpg";
import { TestimonialHome } from "../components/HomeComponents/TestimonialHome";
import { Footer } from "../components/Global/Footer";
import { useSelector, useDispatch } from "react-redux";
import { toggleMobileMenu, toggleMobileCatag } from "../slices/mobilemenuSlice";

export default function Home({ products }) {
  // modal variables
  const [modalView, setModalView] = useState(true);

  // notification toast
  const [notiView, setNotiView] = useState(true);

  // Mobile Menus
  const mobileMenu = useSelector((state) => state.mobilemenu.mobileMenuValue);
  const mobileCatag = useSelector((state) => state.mobilemenu.mobileCatagValue);
  const dispatch = useDispatch();

  return (
    <div>
      <Head>
        <title>Anon - eCommerce Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></Script>

      <main>
        {/* MODAL */}
        <div
          onClick={
            mobileCatag
              ? () => dispatch(toggleMobileCatag())
              : () => dispatch(toggleMobileMenu())
          }
          className={mobileMenu || mobileCatag ? "overlay active" : "overlay"}
          data-overlay
        ></div>

        <div className={modalView ? "modal" : "modal closed"} data-modal>
          <div
            className="modal-close-overlay"
            onClick={() => {
              setModalView(false);
            }}
            data-modal-overlay
          ></div>

          <div className="modal-content">
            <button
              className="modal-close-btn"
              onClick={() => {
                setModalView(false);
              }}
              data-modal-close
            >
              <ion-icon name="close-outline"></ion-icon>
            </button>

            <div className="newsletter-img">
              <Image
                src={modalPic}
                alt="subscribe newsletter"
                width="400"
                height="400"
              />
            </div>

            <div className="newsletter">
              <form action="#">
                <div className="newsletter-header">
                  <h3 className="newsletter-title">Subscribe Newsletter.</h3>

                  <p className="newsletter-desc">
                    Subscribe the <b>Anon</b> to get latest products and
                    discount update.
                  </p>
                </div>

                <input
                  type="email"
                  name="email"
                  className="email-field"
                  placeholder="Email Address"
                  required
                />

                <button type="submit" className="btn-newsletter">
                  Subscribe
                </button>
              </form>
            </div>
          </div>
        </div>

        {/* <!--
        - NOTIFICATION TOAST
        --> */}

        <div
          className={
            notiView ? "notification-toast" : "notification-toast closed"
          }
          data-toast
        >
          <button
            className="toast-close-btn"
            onClick={() => {
              setNotiView(false);
            }}
            data-toast-close
          >
            <ion-icon name="close-outline"></ion-icon>
          </button>

          <div className="toast-banner">
            <Image
              src={jewellery1}
              alt="Rose Gold Earrings"
              width="80"
              height="70"
            />
          </div>

          <div className="toast-detail">
            <p className="toast-message">Someone in new just bought</p>

            <p className="toast-title">Rose Gold Earrings</p>

            <p className="toast-meta">
              <time dateTime="PT2M">2 Minutes</time> ago
            </p>
          </div>
        </div>

        <Navigation />

        {/* BANNER */}
        <HomeBanner />

        {/* CATEGORY */}
        <HomeCategory />

        {/* PRODUCT CONTAINER */}
        <ProductContainer />
        <TestimonialHome />
      </main>
      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  const client = createClient({
    projectId: "wv50dhu8",
    dataset: "production",
    useCdn: true,
  });
  const query = `*[_type=="product"]`;
  const products = await client.fetch(query);
  return {
    props: {
      products,
    },
  };
}
