import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { createClient } from "next-sanity";
import { Navigation } from "../components/Navigation";
import Script from "next/script";
import { HomeBanner } from "../components/HomeBanner";
import { HomeCategory } from "../components/HomeCategory";
import { ProductContainer } from "../components/ProductContainer";
import { useState } from "react";
import modalPic from "../public/images/newsletter.png";
import jewellery1 from "../public/images/products/jewellery-1.jpg";
import { TestimonialHome } from "../components/TestimonialHome";
import payment from "../public/images/payment.png";

export default function Home({ products }) {
  // modal variables
  const [modalView, setModalView] = useState(true);

  // notification toast
  const [notiView, setNotiView] = useState(true);

  // Mobile Nav Menu
  const [mobileMenu, setMobileMenu] = useState(false);

  const mobileMenuCloseFunc = () => {
    setMobileMenu(false);
  };

  // Mobile Category Menu
  const [mobileCatagMenu, setMobileCatagMenu] = useState(false);

  const mobileCatagMenuCloseFunc = () => {
    setMobileCatagMenu(false);
  };
  return (
    <div>
      <Head>
        <title>Anon - eCommerce Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></Script>

      <main>
        {/* MODAL */}
        <div
          onClick={
            mobileCatagMenu ? mobileCatagMenuCloseFunc : mobileMenuCloseFunc
          }
          className={
            mobileMenu || mobileCatagMenu ? "overlay active" : "overlay"
          }
          data-overlay
        ></div>

        <div className={modalView ? "modal" : "modal closed"} data-modal>
          <div
            className="modal-close-overlay"
            onClick={() => {
              setModalView(false);
            }}
            data-modal-overlay
          ></div>

          <div className="modal-content">
            <button
              className="modal-close-btn"
              onClick={() => {
                setModalView(false);
              }}
              data-modal-close
            >
              <ion-icon name="close-outline"></ion-icon>
            </button>

            <div className="newsletter-img">
              <Image
                src={modalPic}
                alt="subscribe newsletter"
                width="400"
                height="400"
              />
            </div>

            <div className="newsletter">
              <form action="#">
                <div className="newsletter-header">
                  <h3 className="newsletter-title">Subscribe Newsletter.</h3>

                  <p className="newsletter-desc">
                    Subscribe the <b>Anon</b> to get latest products and
                    discount update.
                  </p>
                </div>

                <input
                  type="email"
                  name="email"
                  className="email-field"
                  placeholder="Email Address"
                  required
                />

                <button type="submit" className="btn-newsletter">
                  Subscribe
                </button>
              </form>
            </div>
          </div>
        </div>

        {/* <!--
        - NOTIFICATION TOAST
        --> */}

        <div
          className={
            notiView ? "notification-toast" : "notification-toast closed"
          }
          data-toast
        >
          <button
            className="toast-close-btn"
            onClick={() => {
              setNotiView(false);
            }}
            data-toast-close
          >
            <ion-icon name="close-outline"></ion-icon>
          </button>

          <div className="toast-banner">
            <Image
              src={jewellery1}
              alt="Rose Gold Earrings"
              width="80"
              height="70"
            />
          </div>

          <div className="toast-detail">
            <p className="toast-message">Someone in new just bought</p>

            <p className="toast-title">Rose Gold Earrings</p>

            <p className="toast-meta">
              <time dateTime="PT2M">2 Minutes</time> ago
            </p>
          </div>
        </div>

        <Navigation
          mobileMenu={mobileMenu}
          mobileCatagMenu={mobileCatagMenu}
          mobileMenuCloseFunc={mobileMenuCloseFunc}
          setMobileMenu={setMobileMenu}
          setMobileCatagMenu={setMobileCatagMenu}
        />

        {/* BANNER */}
        <HomeBanner />

        {/* CATEGORY */}
        <HomeCategory />

        {/* PRODUCT CONTAINER */}
        <ProductContainer
          mobileMenu={mobileMenu}
          mobileCatagMenu={mobileCatagMenu}
          mobileMenuCloseFunc={mobileMenuCloseFunc}
          mobileCatagMenuCloseFunc={mobileCatagMenuCloseFunc}
        />
        <TestimonialHome />
      </main>

      <footer>
        <div className="footer-category">
          <div className="container">
            <h2 className="footer-category-title">Brand directory</h2>

            <div className="footer-category-box">
              <h3 className="category-box-title">Fashion :</h3>

              <a href="#" className="footer-category-link">
                T-shirt
              </a>
              <a href="#" className="footer-category-link">
                Shirts
              </a>
              <a href="#" className="footer-category-link">
                shorts & jeans
              </a>
              <a href="#" className="footer-category-link">
                jacket
              </a>
              <a href="#" className="footer-category-link">
                dress & frock
              </a>
              <a href="#" className="footer-category-link">
                innerwear
              </a>
              <a href="#" className="footer-category-link">
                hosiery
              </a>
            </div>

            <div className="footer-category-box">
              <h3 className="category-box-title">footwear :</h3>

              <a href="#" className="footer-category-link">
                sport
              </a>
              <a href="#" className="footer-category-link">
                formal
              </a>
              <a href="#" className="footer-category-link">
                Boots
              </a>
              <a href="#" className="footer-category-link">
                casual
              </a>
              <a href="#" className="footer-category-link">
                cowboy shoes
              </a>
              <a href="#" className="footer-category-link">
                safety shoes
              </a>
              <a href="#" className="footer-category-link">
                Party wear shoes
              </a>
              <a href="#" className="footer-category-link">
                Branded
              </a>
              <a href="#" className="footer-category-link">
                Firstcopy
              </a>
              <a href="#" className="footer-category-link">
                Long shoes
              </a>
            </div>

            <div className="footer-category-box">
              <h3 className="category-box-title">jewellery :</h3>

              <a href="#" className="footer-category-link">
                Necklace
              </a>
              <a href="#" className="footer-category-link">
                Earrings
              </a>
              <a href="#" className="footer-category-link">
                Couple rings
              </a>
              <a href="#" className="footer-category-link">
                Pendants
              </a>
              <a href="#" className="footer-category-link">
                Crystal
              </a>
              <a href="#" className="footer-category-link">
                Bangles
              </a>
              <a href="#" className="footer-category-link">
                bracelets
              </a>
              <a href="#" className="footer-category-link">
                nosepin
              </a>
              <a href="#" className="footer-category-link">
                chain
              </a>
              <a href="#" className="footer-category-link">
                Earrings
              </a>
              <a href="#" className="footer-category-link">
                Couple rings
              </a>
            </div>

            <div className="footer-category-box">
              <h3 className="category-box-title">cosmetics :</h3>

              <a href="#" className="footer-category-link">
                Shampoo
              </a>
              <a href="#" className="footer-category-link">
                Bodywash
              </a>
              <a href="#" className="footer-category-link">
                Facewash
              </a>
              <a href="#" className="footer-category-link">
                makeup kit
              </a>
              <a href="#" className="footer-category-link">
                liner
              </a>
              <a href="#" className="footer-category-link">
                lipstick
              </a>
              <a href="#" className="footer-category-link">
                prefume
              </a>
              <a href="#" className="footer-category-link">
                Body soap
              </a>
              <a href="#" className="footer-category-link">
                scrub
              </a>
              <a href="#" className="footer-category-link">
                hair gel
              </a>
              <a href="#" className="footer-category-link">
                hair colors
              </a>
              <a href="#" className="footer-category-link">
                hair dye
              </a>
              <a href="#" className="footer-category-link">
                sunscreen
              </a>
              <a href="#" className="footer-category-link">
                skin loson
              </a>
              <a href="#" className="footer-category-link">
                liner
              </a>
              <a href="#" className="footer-category-link">
                lipstick
              </a>
            </div>
          </div>
        </div>

        <div className="footer-nav">
          <div className="container">
            <ul className="footer-nav-list">
              <li className="footer-nav-item">
                <h2 className="nav-title">Popular Categories</h2>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Fashion
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Electronic
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Cosmetic
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Health
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Watches
                </a>
              </li>
            </ul>

            <ul className="footer-nav-list">
              <li className="footer-nav-item">
                <h2 className="nav-title">Products</h2>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Prices drop
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  New products
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Best sales
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Contact us
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Sitemap
                </a>
              </li>
            </ul>

            <ul className="footer-nav-list">
              <li className="footer-nav-item">
                <h2 className="nav-title">Our Company</h2>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Delivery
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Legal Notice
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Terms and conditions
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  About us
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Secure payment
                </a>
              </li>
            </ul>

            <ul className="footer-nav-list">
              <li className="footer-nav-item">
                <h2 className="nav-title">Services</h2>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Prices drop
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  New products
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Best sales
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Contact us
                </a>
              </li>

              <li className="footer-nav-item">
                <a href="#" className="footer-nav-link">
                  Sitemap
                </a>
              </li>
            </ul>

            <ul className="footer-nav-list">
              <li className="footer-nav-item">
                <h2 className="nav-title">Contact</h2>
              </li>

              <li className="footer-nav-item flex">
                <div className="icon-box">
                  <ion-icon name="location-outline"></ion-icon>
                </div>

                <address className="content">
                  419 State 414 Rte Beaver Dams, New York(NY), 14812, USA
                </address>
              </li>

              <li className="footer-nav-item flex">
                <div className="icon-box">
                  <ion-icon name="call-outline"></ion-icon>
                </div>

                <a href="tel:+607936-8058" className="footer-nav-link">
                  (607) 936-8058
                </a>
              </li>

              <li className="footer-nav-item flex">
                <div className="icon-box">
                  <ion-icon name="mail-outline"></ion-icon>
                </div>

                <a href="mailto:example@gmail.com" className="footer-nav-link">
                  example@gmail.com
                </a>
              </li>
            </ul>

            <ul className="footer-nav-list">
              <li className="footer-nav-item">
                <h2 className="nav-title">Follow Us</h2>
              </li>

              <li>
                <ul className="social-link">
                  <li className="footer-nav-item">
                    <a href="#" className="footer-nav-link">
                      <ion-icon name="logo-facebook"></ion-icon>
                    </a>
                  </li>

                  <li className="footer-nav-item">
                    <a href="#" className="footer-nav-link">
                      <ion-icon name="logo-twitter"></ion-icon>
                    </a>
                  </li>

                  <li className="footer-nav-item">
                    <a href="#" className="footer-nav-link">
                      <ion-icon name="logo-linkedin"></ion-icon>
                    </a>
                  </li>

                  <li className="footer-nav-item">
                    <a href="#" className="footer-nav-link">
                      <ion-icon name="logo-instagram"></ion-icon>
                    </a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </div>

        <div className="footer-bottom">
          <div className="container">
            <Image src={payment} alt="payment method" className="payment-img" />

            <p className="copyright">
              Copyright &copy; <a href="#">Anon</a> all rights reserved.
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}

export async function getServerSideProps(context) {
  const client = createClient({
    projectId: "wv50dhu8",
    dataset: "production",
    useCdn: true,
  });
  const query = `*[_type=="product"]`;
  const products = await client.fetch(query);
  return {
    props: {
      products,
    },
  };
}
